# Generated by Django 4.2.16 on 2024-10-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
