# Generated by Django 4.2.16 on 2024-10-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_activitylog_answer_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
