# Generated by Django 4.2.16 on 2024-10-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answersheet_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='file',
            field=models.FileField(upload_to='answer_sheets/'),
        ),
    ]
