# Generated by Django 4.2.16 on 2024-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_answersheet_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='marks',
            field=models.JSONField(default=dict),
        ),
    ]
